# Generated by Django 4.0.3 on 2022-03-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moeda', '0002_auto_20220317_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotacao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='cotacao',
            unique_together={('moeda', 'base', 'data')},
        ),
    ]
